<?php

namespace Database\Seeders;

use App\Models\Voter;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $voters = [
            [
                'first_name' => 'Charlotte',
                'last_name' => 'Mercado',
                'birthdate' => '2004-07-07',
                'gender' => 'Male',
                'contact_information' => '09123456789',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Carlos Alfonso',
                'last_name' => 'Perez',
                'birthdate' => '2003-04-08',
                'gender' => 'Female',
                'contact_information' => '09123456789',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Jade John Lloyd',
                'last_name' => 'de Lara',
                'birthdate' => '2003-12-25',
                'gender' => 'Male',
                'contact_information' => '09123456789',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Maria Sophia',
                'last_name' => 'Cruz',
                'birthdate' => '2002-03-15',
                'gender' => 'Female',
                'contact_information' => '09187654321',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Jose Miguel',
                'last_name' => 'Santos',
                'birthdate' => '2001-09-22',
                'gender' => 'Male',
                'contact_information' => '09198765432',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Isabella Grace',
                'last_name' => 'Reyes',
                'birthdate' => '2004-01-30',
                'gender' => 'Female',
                'contact_information' => '09165432198',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Gabriel Luis',
                'last_name' => 'Fernandez',
                'birthdate' => '2003-06-18',
                'gender' => 'Male',
                'contact_information' => '09171234567',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Andrea Mae',
                'last_name' => 'Mendoza',
                'birthdate' => '2002-11-05',
                'gender' => 'Female',
                'contact_information' => '09182345678',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Rafael Angelo',
                'last_name' => 'Torres',
                'birthdate' => '2001-08-14',
                'gender' => 'Male',
                'contact_information' => '09193456789',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Angelica Rose',
                'last_name' => 'Garcia',
                'birthdate' => '2004-05-20',
                'gender' => 'Female',
                'contact_information' => '09164567890',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Marco Antonio',
                'last_name' => 'Ramos',
                'birthdate' => '2003-02-28',
                'gender' => 'Male',
                'contact_information' => '09175678901',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Patricia Anne',
                'last_name' => 'Morales',
                'birthdate' => '2002-10-12',
                'gender' => 'Female',
                'contact_information' => '09186789012',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Daniel Joseph',
                'last_name' => 'Lopez',
                'birthdate' => '2001-07-03',
                'gender' => 'Male',
                'contact_information' => '09197890123',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Samantha Joy',
                'last_name' => 'Pascual',
                'birthdate' => '2004-12-09',
                'gender' => 'Female',
                'contact_information' => '09168901234',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Vincent Paul',
                'last_name' => 'Santiago',
                'birthdate' => '2003-04-27',
                'gender' => 'Male',
                'contact_information' => '09179012345',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Nicole Marie',
                'last_name' => 'Bautista',
                'birthdate' => '2002-08-16',
                'gender' => 'Female',
                'contact_information' => '09180123456',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Kenneth James',
                'last_name' => 'Villanueva',
                'birthdate' => '2001-05-11',
                'gender' => 'Male',
                'contact_information' => '09191234567',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Kristine Faith',
                'last_name' => 'Aquino',
                'birthdate' => '2004-09-24',
                'gender' => 'Female',
                'contact_information' => '09162345678',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Ryan Michael',
                'last_name' => 'Dela Rosa',
                'birthdate' => '2003-01-19',
                'gender' => 'Male',
                'contact_information' => '09173456789',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Stephanie Luz',
                'last_name' => 'Navarro',
                'birthdate' => '2002-06-07',
                'gender' => 'Female',
                'contact_information' => '09184567890',
                'imagepath' => 'test',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('voters')->insert($voters);
    }
}